
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "${FRONT_PORT}:${NODEJS_SERVER_INSIDE_CONTAINER_PORT}"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:11
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_pmtde:/var/lib/mysql

volumes:
  db_pmtde:
