FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .
ARG NODEJS_SERVER_INSIDE_CONTAINER_PORT=3000
ENV NODEJS_SERVER_INSIDE_CONTAINER_PORT=${NODEJS_SERVER_INSIDE_CONTAINER_PORT}
ENV NODE_ENV=production
EXPOSE ${NODEJS_SERVER_INSIDE_CONTAINER_PORT}
CMD ["npm", "start"]
